/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e95796a43731756f7e1cb60
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import { DateTimePicker } from "material-ui-pickers";

// Custom Actions


// START IMPORT ACTIONS
import TestActions from "../redux/actions/TestActions";

// END IMPORT ACTIONS

/** APIs

* actionsTest.create
*	@description CRUD ACTION create
*
* actionsTest.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsTest.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*

**/

class TestEdit extends Component {
  // Init test
  constructor(props) {
    super(props);
    this.state = {
      test: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsTest.loadTest(this.props.match.params.id);
    }
    
  }

  // Insert props test in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      test: props.test
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.test._id) {
      this.props.actionsTest.saveTest(this.state.test).then(data => {
        this.props.history.push("/tests/");
      });
    } else {
      this.props.actionsTest.createTest(this.state.test).then(data => {
        this.props.history.push("/tests/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Test Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          <DateTimePicker
            id="date"
            label="Date"
            className="mt-20 mb-20"
            ampm={false}
            value={
              this.state.test.date
                ? new Date(this.state.test.date)
                : null
            }
            onChange={Utils.handleChangeDate.bind(this, "test", "date")}
            fullWidth
            autoOk
            disableFuture
          />
          
          
          <TextField
            id="name"
            label="Name"
            value={this.state.test.name || ""}
            onChange={Utils.handleChange.bind(this, "test")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="number"
            label="Number"
            value={this.state.test.number || ""}
            onChange={Utils.handleChange.bind(this, "test")}
            type="number"
            margin="normal"
            fullWidth
          />
          

          {/* Footer */}
          <div className="footer-card">
            <Link to="/tests/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsTest: bindActionCreators(TestActions, dispatch),
  };
};

// Validate types
TestEdit.propTypes = { 
  actionsTest: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    test: state.TestEditReducer.test
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(TestEdit);
